[UI] - Add support for adding Facets and Pagination to URL
klevultd/frontend-sdk pull request #535
Opened 2023-12-13 12:14 UTC by nikhil-narayana-klevu

1. Added props for should add facets and pagination values to URL
2. Support for reading the values from URL

2023-12-14 06:21 UTC, nikhil-narayana-klevu commented
@rallu Merged your PR, please review now.

2023-12-14 08:29 UTC, rallu requested changes
Code looks good, but the description of the PR needs improvement. That will go to release notes so we need to be very clear about the description.

2023-12-14 08:49 UTC, nikhil-narayana-klevu commented
> Code looks good, but the description of the PR needs improvement. That will go to release notes so we need to be very clear about the description.

Changed the description, let me know if still needs work.

2023-12-15 09:48 UTC, rallu approved these changes

2023-12-15 09:48 UTC, merged